name: Health Check for Deployed Application

on:
  push:
    branches:
      - main # Trigger health check after any push to the main branch
  schedule:
    - cron: "0 0 * * *" # Scheduled to run once a day at midnight UTC (adjust as needed)

jobs:
  health_check:
    runs-on: ubuntu-20.04

    steps:
      - name: Check deployed service health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-solitary-feather-9307.fly.dev/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Retry 3 times if it fails
          retry-delay: 5s # Retry delay between attempts
          retry-all: false # Do not retry for 404 or other client errors
